name: msfoole
version: 0.0.1
description: 基于swoole的简易微服务框架
environments:
  APPLICATION__DEBUG: false
  MSFOOLE__HOST: "0.0.0.0"
  MSFOOLE__PORT: 9555
  MSFOOLE__OPTION__MAX_REQUEST: 0
  MSFOOLE__OPTION__DAEMONIZE: 0
  MSFOOLE__OPTION__LOG_LEVEL: 0
  MSFOOLE__OPTION__LOG_FILE: msfoole.log
  MSFOOLE__OPTION__REQUEST_SLOWLOG_FILE: trace.log