name: msfoole
version: 1.0.0
description: 基于swoole的多进程API服务框架
environments:
  MSFOOLE__HOST: "0.0.0.0"
  MSFOOLE__PORT: 9555
  MSFOOLE__SSL: false
  MSFOOLE__MONITOR__PATH: app/,vendor/julibo/msfoole/src/
  MSFOOLE__MONITOR__INTERVAL: 10
  MSFOOLE__WEBSOCKET__KEY: 700040D41F47592C
  MSFOOLE__WEBSOCKET__VI: 7AF3C134BEAA99E5
  MSFOOLE__WEBSOCKET__SIGN: null
  MSFOOLE__WEBSOCKET__NAMESPACE: \App\Controller\Robot\
  MSFOOLE__WEBSOCKET__LOGINCLASS: \App\Service\Robot
  MSFOOLE__WEBSOCKET__LOGINACTION: login
  MSFOOLE__TABLE__SIZE: 1024
  MSFOOLE__CACHE__SIZE: 8192
  MSFOOLE__CACHE__RATE: 1
  MSFOOLE__CACHE__DATA_SIZE: 65536
  MSFOOLE__CHANNEL__SWITCH: on
  MSFOOLE__CHANNEL__SIZE: 65536
  MSFOOLE__CHANNEL__POOL: 1
  MSFOOLE__OPTION__WORKER_NUM: 1
  MSFOOLE__OPTION__MAX_REQUEST: 0
  MSFOOLE__OPTION__DAEMONIZE: 0
  MSFOOLE__OPTION__LOG_LEVEL: 0
  MSFOOLE__OPTION__LOG_FILE: msfoole.log
  MSFOOLE__OPTION__REQUEST_SLOWLOG_FILE: trace.log
  MSFOOLE__OPTION__OPEN_HTTP2_PROTOCOL: false
  MSFOOLE__OPTION__RELOAD_ASYNC: false
  MSFOOLE__OPTION__HEARTBEAT_CHECK_INTERVAL: 1
  MSFOOLE__OPTION__HEARTBEAT_IDLE_TIME: 120